var = input('Digite algo:')
print('O tipo primitivo deste valor é:', type(var))
print('O valor digitado é uma letra:', var.isalpha())
print('O valor digitado é um numero:', var.isnumeric())
print('É somente espaços:', var.isspace())
print('Possui letras maisuculas:', var.isupper())
print('______Variavel varrida_______')
